name: AI Auto-Documentation

on:
  push:
    branches:
      - main

jobs:
  generate_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: DEBUG - Show Workflow File Content
        run: |
          echo "--- Workflow file content ---"
          cat .github/workflows/documenter.yml
          echo "---------------------------"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Get changed Python files
        id: changed_files
        run: |
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD | grep '\.py$' || echo "")
          echo "files=${CHANGED_FILES}" >> $GITHUB_OUTPUT

      - name: Generate documentation
        if: steps.changed_files.outputs.files != ''

        env:
          # متغیرهای مربوط به Documenter
          DOCUMENTER_LLM_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          DOCUMENTER_LLM_MODEL: "gpt-4-turbo"
          DOCUMENTER_LLM_BASE_URL: "https://api.openai.com/v1"  #  <-- خط جدید
        
          # متغیرهای مورد نیاز برای Analyzer
          ANALYZER_LLM_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANALYZER_LLM_MODEL: "gpt-4-turbo"
          ANALYZER_LLM_BASE_URL: "https://api.openai.com/v1"   #  <-- خط جدید
        run: |
          for file in ${{ steps.changed_files.outputs.files }}
          do
            # دستور زیر اصلاح شده تا آرگومان‌های اضافه را نداشته باشد
            python run_doc_generator.py --project-root "." --file-path "$file" --output-dir "docs"
          done
      
      - name: Commit and push documentation
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: ✨ Automatically generate documentation"
          file_pattern: "docs/**/*.md"
          commit_user_name: "AI Doc Bot"
          commit_user_email: "ai-doc-bot@users.noreply.github.com"
